{% set name = "tobac" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tobac-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 38d5653133449ceef6d49df393d717275b5a0bdb4fa2ca3fe1f36c2289307aa6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-image
    - pandas
    - pytables
    - matplotlib-base
    - iris
    - xarray
    - cf-units
    - cartopy
    - trackpy

test:
  imports:
    - tobac
    - tobac.testing
  source_files:
    - tobac/tests/test_import.py
    - tobac/tests/test_sample_data.py
    - tobac/tests/test_feature_detection.py
    - tobac/tests/test_segmentation.py
    - tobac/tests/test_tracking.py
  requires:
    - pytest
  commands:
    - pytest tobac/tests
about:
  home: https://github.com/tobac-project/tobac
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tracking and Object-Based Analysis of Clouds

  description: tobac is a flexible frameork for cloud tracking of different types of datasets
  doc_url: http://tobac.readthedocs.io/
  dev_url: https://github.com/tobac-project/tobac

extra:
  recipe-maintainers:
    - freemansw1
    - mheikenfeld
    - w-k-jones
