travis:
  secure:
    BINSTAR_TOKEN: Tj/x5VJhdRBLg7g0oIzn8ZJVOsBx/i4+TtcNFKFeYg1sQG8aOwfgQ+kjraWMHT+OHY3qNxr6jOV3mCrKsPCBMZcaCQ/wUdCVhOQornhIk52OjKAZxej94ee0WAjkVvoiT5qUlqrvNtMuxH5MTEHxRRCy40J6IYc0EdWy6UhQdjYdiHbpnRKQpzK7PX6CKXVFvPbbVnq4itS5gYdrNecCofFxD9dxbMQWwT6GyM9Ym+/5bCQKBfBTpEe2uZ3wiMwhuGaQWMXuYRhSe7YnPGTeg9xwL+A8rImGx089Y4sYzR32oIlDHKKUmXvcGM6lq9JR7nqhHxmi4EbuDaLhI1NG3dXwFRClHEtEViSAKgnx30z+PsYJ47yEBrVPOTFZUTKxEh1ENIJ5yxr4d3K5Wyu723FV9vYq6qimfHOLrDqIorMFPY8WvpGNWSOtkGJHoNG+HNQE2Revf1hjk6jtOhHVqy68ydf/4QL6jCDxMUDXkfABJ9/3nV9e+6Fgl7EQwJi/Ub/bw0lYiLeW3v63fxCrwq12gMl0KG2lMdiY323veLwgB1ZwqM9/7jG5jhZTR5Pwlbv/az5u/vySJjmWdAz1lUYa5m37zb/2myE13cNlStPJIuUwtdwT+NZVjuuKYs0aAba/LpFZyq+GhZUJD7vBSCgTTXk5RBkX4XnN79aU/As=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
